spring.application.name=readora-backend

# ===============================
# Server
# ===============================

server.port=8080


# ===============================
# PostgreSQL
# ===============================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# HikariCP
# ===============================

# Retire connections before PostgreSQL / hosting provider closes them.
# 5 minutes
spring.datasource.hikari.max-lifetime=300000

# Periodically keep idle connections alive.
# 2 minutes (must be shorter than max-lifetime)
spring.datasource.hikari.keepalive-time=120000

# Maximum time to wait for a connection from the pool.
# 30 seconds
spring.datasource.hikari.connection-timeout=30000

# Maximum time Hikari waits when validating a connection.
# 5 seconds
spring.datasource.hikari.validation-timeout=5000


# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


jwt.secret=${JWT_SECRET}
jwt.access-expiration=900000000000

refresh-token.expiration=2592000000
refresh-token.expiration-days=7

# Email
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Email verification
app.base-url=http://localhost:8080
email-verification.expiration-hours=24


password-reset.otp-expiration-minutes=10
password-reset.max-attempts=5


google.client-id=${GOOGLE_CLIENT_ID}


springdoc.swagger-ui.persist-authorization=true


cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}


# Multipart upload limits
spring.servlet.multipart.max-file-size=220MB
spring.servlet.multipart.max-request-size=350MB

# Cloudinary per-file size limits (bytes)
# Cover: 10MB
# PDF: 100MB
# Audio: 200MB
cloudinary.max-cover-size=10485760
cloudinary.max-pdf-size=104857600
cloudinary.max-audio-size=209715200